
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9lyCuH2GqFv89OW58ofkSPcRYIo4r7MY',
    appId: '1:742407555269:android:a4f3664c7725d40abf88ac',
    messagingSenderId: '742407555269',
    projectId: 'antalya-taxi',
    databaseURL: 'https://antalya-taxi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'antalya-taxi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEI71PNRjFK_T15l-9ZWfYM--bBed2L7E',
    appId: '1:742407555269:ios:34150e4ff16f8a44bf88ac',
    messagingSenderId: '742407555269',
    projectId: 'antalya-taxi',
    databaseURL: 'https://antalya-taxi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'antalya-taxi.appspot.com',
    iosBundleId: 'taksi.antalya.taksi.rider',
  );

}